"""add Order table

Revision ID: f4f6e0bd62df
Revises: 6050fa79dfe9
Create Date: 2025-08-18 11:32:59.426601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4f6e0bd62df"
down_revision: Union[str, Sequence[str], None] = "6050fa79dfe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "User", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="unique")
    # ### end Alembic commands ###
