"""add OrdeProducts table

Revision ID: c0549d5d0e52
Revises: f4f6e0bd62df
Create Date: 2025-08-18 15:12:27.205862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0549d5d0e52"
down_revision: Union[str, Sequence[str], None] = "f4f6e0bd62df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "OrderProducts",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["Order.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["Product.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Order", sa.Column("comment", sa.String(), nullable=False))
    op.create_unique_constraint(None, "Order", ["promo_code"])
    op.drop_column("Order", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Order",
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "Order", type_="unique")
    op.drop_column("Order", "comment")
    op.drop_table("OrderProducts")
    # ### end Alembic commands ###
