"""updated parameters of all models, reworked their interaction, added ORM connections

Revision ID: 51efdb5bee15
Revises: fc52f269d949
Create Date: 2025-09-02 12:14:51.296227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51efdb5bee15"
down_revision: Union[str, Sequence[str], None] = "fc52f269d949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "total_sum", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(op.f("Profile_user_id_key"), "Profile", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("Profile_user_id_key"),
        "Profile",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "Order", "total_sum", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
