"""refacton column name for order_product

Revision ID: 7845fdf4f35d
Revises: a96ece410845
Create Date: 2025-10-10 15:18:08.061792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7845fdf4f35d"
down_revision: Union[str, Sequence[str], None] = "a96ece410845"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "total_price", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.drop_column("orders", "total_sum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "total_sum",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "total_price")
    # ### end Alembic commands ###
