"""add new revision, The dates of creation and updating of data in tables are moved to a separate mixin

Revision ID: aec5eee719a8
Revises: b15fabb336c2
Create Date: 2025-12-09 12:13:43.227969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aec5eee719a8"
down_revision: Union[str, Sequence[str], None] = "b15fabb336c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_products",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "cart_products",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "cart_products",
        "current_price",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.add_column(
        "carts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "order_products",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "order_products",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "order_products",
        "current_price",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.add_column(
        "orders",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "posts",
        "title",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.add_column(
        "products",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "price",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.add_column(
        "profiles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "profiles",
        "address",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "profiles",
        "bio",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("profiles_name_key"), "profiles", type_="unique")
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("users_login_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "login")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_login_key"),
        "users",
        ["login"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "email")
    op.create_unique_constraint(
        op.f("profiles_name_key"),
        "profiles",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "profiles",
        "bio",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "address",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_column("profiles", "updated_at")
    op.alter_column(
        "products",
        "price",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("products", "updated_at")
    op.alter_column(
        "posts",
        "title",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("posts", "updated_at")
    op.drop_column("orders", "updated_at")
    op.alter_column(
        "order_products",
        "current_price",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("order_products", "updated_at")
    op.drop_column("order_products", "created_at")
    op.drop_column("carts", "updated_at")
    op.alter_column(
        "cart_products",
        "current_price",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("cart_products", "updated_at")
    op.drop_column("cart_products", "created_at")
    # ### end Alembic commands ###
