"""add new revision, The user model's email field has been changed to login.

Revision ID: 1e820c34d02f
Revises: aec5eee719a8
Create Date: 2025-12-09 12:23:31.517966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e820c34d02f"
down_revision: Union[str, Sequence[str], None] = "aec5eee719a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login", sa.String(), nullable=False))
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["login"])
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "login")
    # ### end Alembic commands ###
