"""add count column for OrdeProducts table

Revision ID: 0285241f668b
Revises: c0549d5d0e52
Create Date: 2025-08-18 15:19:06.269082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0285241f668b"
down_revision: Union[str, Sequence[str], None] = "c0549d5d0e52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "OrderProducts",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("OrderProducts", "count")
    # ### end Alembic commands ###
