"""add current_price column in order_product

Revision ID: a96ece410845
Revises: beb141442aa5
Create Date: 2025-10-08 15:14:14.410920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a96ece410845"
down_revision: Union[str, Sequence[str], None] = "beb141442aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_products",
        sa.Column(
            "current_price", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_products", "current_price")
    # ### end Alembic commands ###
