"""add cascade delete by User table

Revision ID: 27a3e04f4c28
Revises: 6035ae7bb8b1
Create Date: 2025-08-11 13:44:59.847703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27a3e04f4c28"
down_revision: Union[str, Sequence[str], None] = "6035ae7bb8b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Profile", ["user_id"])
    op.create_unique_constraint(None, "User", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="unique")
    op.drop_constraint(None, "Profile", type_="unique")
    # ### end Alembic commands ###
