"""revork models user and profile

Revision ID: c956b573a464
Revises: 7845fdf4f35d
Create Date: 2025-12-05 10:55:20.771349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c956b573a464'
down_revision: Union[str, Sequence[str], None] = '7845fdf4f35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('address', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['name'])
    op.drop_column('profiles', 'married')
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    op.drop_column('users', 'email')
    op.drop_column('users', 'address')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'login')
    op.add_column('profiles', sa.Column('married', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'address')
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###
