"""add new add field in model orders (total_quantity)

Revision ID: 93021f415701
Revises: 5f0c0d3011b9
Create Date: 2025-12-21 18:33:13.445860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93021f415701"
down_revision: Union[str, Sequence[str], None] = "5f0c0d3011b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("total_quantity", sa.Integer(), nullable=False)
    )
    op.add_column(
        "refresh_tokens", sa.Column("token", sa.Text(), nullable=False)
    )
    op.drop_constraint(
        op.f("refresh_tokens_token_hash_key"), "refresh_tokens", type_="unique"
    )
    op.create_unique_constraint(None, "refresh_tokens", ["token"])
    op.drop_column("refresh_tokens", "token_hash")
    op.drop_column("refresh_tokens", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "token_hash", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "refresh_tokens", type_="unique")
    op.create_unique_constraint(
        op.f("refresh_tokens_token_hash_key"),
        "refresh_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("refresh_tokens", "token")
    op.drop_column("orders", "total_quantity")
    # ### end Alembic commands ###
