"""add Cart and CartItem tables

Revision ID: 33bfd9f8391e
Revises: 83c8dd080044
Create Date: 2025-08-30 17:59:55.717692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33bfd9f8391e"
down_revision: Union[str, Sequence[str], None] = "83c8dd080044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "OrderProducts",
        sa.Column(
            "quantity", sa.Integer(), server_default="1", nullable=False
        ),
    )
    op.create_unique_constraint(
        "idx_unique_order_product", "OrderProducts", ["order_id", "product_id"]
    )
    op.drop_column("OrderProducts", "count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "OrderProducts",
        sa.Column(
            "count",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        "idx_unique_order_product", "OrderProducts", type_="unique"
    )
    op.drop_column("OrderProducts", "quantity")
    # ### end Alembic commands ###
