"""add parametr by column promo_code for Orde table, promo_code may be None

Revision ID: b8dfaf0c0b35
Revises: 0285241f668b
Create Date: 2025-08-19 12:20:08.773918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8dfaf0c0b35"
down_revision: Union[str, Sequence[str], None] = "0285241f668b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "promo_code", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "promo_code", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
