"""add parametrs for models nullable

Revision ID: 83c8dd080044
Revises: b8dfaf0c0b35
Create Date: 2025-08-19 14:03:39.813182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83c8dd080044"
down_revision: Union[str, Sequence[str], None] = "b8dfaf0c0b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Order", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "Order", "comment", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "Order", "total_sum", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        None, "Order", "User", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "OrderProducts",
        "count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "OrderProducts",
        "count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.drop_constraint(None, "Order", type_="foreignkey")
    op.alter_column(
        "Order", "total_sum", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "Order", "comment", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("Order", "user_id")
    # ### end Alembic commands ###
