"""snapshot current schema

Revision ID: beb141442aa5
Revises: a1c3af93b393
Create Date: 2025-10-04 16:20:09.428844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "beb141442aa5"
down_revision: Union[str, Sequence[str], None] = "a1c3af93b393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_products",
        sa.Column(
            "current_price", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_products", "current_price")
    # ### end Alembic commands ###
