"""add , ondelete=CASCADE by Post and Profile

Revision ID: 5dea4228e3b8
Revises: dc8b8a07951d
Create Date: 2025-07-31 11:24:42.482059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dea4228e3b8"
down_revision: Union[str, Sequence[str], None] = "dc8b8a07951d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("Post_user_id_fkey"), "Post", type_="foreignkey")
    op.create_foreign_key(
        None, "Post", "User", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("Profile_user_id_fkey"), "Profile", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "Profile", "User", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Profile", type_="foreignkey")
    op.create_foreign_key(
        op.f("Profile_user_id_fkey"), "Profile", "User", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "Post", type_="foreignkey")
    op.create_foreign_key(
        op.f("Post_user_id_fkey"), "Post", "User", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
