"""refactor data types from user password LargeBinary

Revision ID: 0358715474ea
Revises: 93021f415701
Create Date: 2025-12-28 16:21:55.888181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0358715474ea'
down_revision: Union[str, Sequence[str], None] = '93021f415701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column(
        'users',
        'password',
        existing_type=sa.VARCHAR(length=64),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="password::bytea"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
