"""add unique=True for Profiles table

Revision ID: fda21cce8bf9
Revises: 86b39930f5ef
Create Date: 2026-01-05 15:44:01.073074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fda21cce8bf9"
down_revision: Union[str, Sequence[str], None] = "86b39930f5ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profiles", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="unique")
    # ### end Alembic commands ###
