"""add onupdate parametr for TimestampMixin model

Revision ID: 86b39930f5ef
Revises: 1b454fc638c7
Create Date: 2026-01-05 11:01:04.119477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86b39930f5ef"
down_revision: Union[str, Sequence[str], None] = "1b454fc638c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
