"""The data types for storing price values in the models have been changed to Integer, and new fields have been added to the order model: original price and discount.

Revision ID: 19f8f61eb46b
Revises: 0358715474ea
Create Date: 2026-01-02 13:58:29.304371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19f8f61eb46b"
down_revision: Union[str, Sequence[str], None] = "0358715474ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands adjusted for safe type conversion ###
    op.alter_column(
        "cart_products",
        "current_price",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        postgresql_using="current_price::integer",
    )
    op.alter_column(
        "order_products",
        "current_price",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        postgresql_using="current_price::integer",
    )
    op.alter_column(
        "products",
        "price",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        postgresql_using="price::integer",
    )
    # добавление новых полей в orders
    op.add_column(
        "orders",
        sa.Column("original_price", sa.Integer(), nullable=False)
    )
    op.add_column(
        "orders",
        sa.Column("discount", sa.Integer(), nullable=True)
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("orders", "discount")
    op.drop_column("orders", "original_price")
    op.alter_column(
        "order_products",
        "current_price",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "cart_products",
        "current_price",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
